name: svgpath
version: 1.0.0
description: SVG path low level transformations toolkit
author: SlickTech
homepage: https://github.com/SlickTech/svgpath

environment:
  sdk: '>=1.24.3 <3.0.0'

dependencies:
  dart2_constant: ^1.0.0

dev_dependencies:
  path: ^1.0.0
  test: ">=0.12.30 <2.0.0"
