name: svgpath
description: SVG path low level transformations toolkit
version: 0.0.1
author: SlickTech
homepage: https://github.com/SlickTech

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  path:
